# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 45ec836e9e336e6befdc3f509a24868e612bd6d88c4af82798889cb3a8078fe46553725b1de7f708ad6f5e1eac9601775320ce63c6337da92f44b9b763275ea0

test:
  secret_key_base: bd1be0fc64a14864270df741bc199a01777fc592f2afadde9de098f85251af95bf739dd7d65bf875d4a6ed3782902269b2600fd0808bdcae97ba8d282b2f5ff5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
